### PR TITLE
Query for Container Apps as there don't seem to be any default templates

### PR DESCRIPTION
**Pull request by samsp-msft**
Q: In the query UI you can customize columns making them auto-size and grouping them. Is it possible to pre-configure that for a query using metadata etc?

### CODE REVIEW

**Comment by samsp-msft** [comment]
Goes towards fixing https://github.com/microsoft/azure-container-apps/issues/635.

Tagging @bigmorty, @bradygaster

**Comment by bradygaster** [comment]
this is a much-needed contribution. i may come up with a few more of these if folks have other needs/asks for reports/pre-canned queries for ACA-hosted compute.

**Comment by samsp-msft** [comment]
@shijatsu - Who needs to review and approve this kind of request?

**Comment by shijatsu** [comment]
> 

These are queries so tagging @noakup  If there is a workbook tag me again

**Pull request merged**
